version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dist
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/mkdir.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_flask.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_flask1.sh
      timeout: 300
      runas: root
